2022-04-16 23:44:48,961   CRITICAL   client.py             Потеряно соединение с сервером.
2022-04-16 23:45:23,854   INFO       client.py             Сформировано presence сообщение: {'action': 'presence', 'time': 1650141923.854075, 'user': {'account_name': 'user1'}}
2022-04-16 23:45:23,877   DEBUG      client.py             Вызвана функция: send_message с параметрами: (<socket.socket fd=400, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58417), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1650141923.854075, 'user': {'account_name': 'user1'}}), {}. Результат работы функции: None. Вызов из функции: init_socket 
2022-04-16 23:45:24,500   DEBUG      client.py             Вызвана функция: get_message с параметрами: (<socket.socket fd=400, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58417), raddr=('127.0.0.1', 7777)>,), {}. Результат работы функции: {'status_code': 200, 'status': 'OK'}. Вызов из функции: init_socket 
2022-04-16 23:45:24,500   DEBUG      client.py             Разбор ответа от сервера: {'status_code': 200, 'status': 'OK'}
2022-04-16 23:45:24,500   INFO       client.py             Установленно соединение с сервером. Ответ сервера: 200: OK
2022-04-16 23:45:24,502   DEBUG      client.py             Запущены процессы получения и отправки сообщений.
2022-04-16 23:45:41,126   DEBUG      client.py             Вызвана функция: send_message с параметрами: (<socket.socket fd=400, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58417), raddr=('127.0.0.1', 7777)>, {'action': 'exit', 'time': 1650141941.1249087, 'account_name': 'user1'}), {}. Результат работы функции: None. Вызов из функции: run 
2022-04-16 23:45:41,126   INFO       client.py             Завершение работы по команде пользователя.
2022-04-16 23:46:17,584   INFO       client.py             Сформировано presence сообщение: {'action': 'presence', 'time': 1650141977.5846229, 'user': {'account_name': 'user'}}
2022-04-16 23:46:17,607   DEBUG      client.py             Вызвана функция: send_message с параметрами: (<socket.socket fd=448, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58444), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1650141977.5846229, 'user': {'account_name': 'user'}}), {}. Результат работы функции: None. Вызов из функции: init_socket 
2022-04-16 23:46:18,202   DEBUG      client.py             Вызвана функция: get_message с параметрами: (<socket.socket fd=448, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58444), raddr=('127.0.0.1', 7777)>,), {}. Результат работы функции: {'status_code': 200, 'status': 'OK'}. Вызов из функции: init_socket 
2022-04-16 23:46:18,203   DEBUG      client.py             Разбор ответа от сервера: {'status_code': 200, 'status': 'OK'}
2022-04-16 23:46:18,203   INFO       client.py             Установленно соединение с сервером. Ответ сервера: 200: OK
2022-04-16 23:46:18,204   DEBUG      client.py             Запущены процессы получения и отправки сообщений.
2022-04-16 23:47:02,299   DEBUG      client.py             Вызвана функция: send_message с параметрами: (<socket.socket fd=448, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58444), raddr=('127.0.0.1', 7777)>, {'action': 'exit', 'time': 1650142022.2975001, 'account_name': 'user'}), {}. Результат работы функции: None. Вызов из функции: run 
2022-04-16 23:47:02,299   INFO       client.py             Завершение работы по команде пользователя.
2022-04-16 23:47:11,743   INFO       client.py             Сформировано presence сообщение: {'action': 'presence', 'time': 1650142031.7439682, 'user': {'account_name': 'test3'}}
2022-04-16 23:47:11,753   INFO       client.py             Сформировано presence сообщение: {'action': 'presence', 'time': 1650142031.7539608, 'user': {'account_name': 'test1'}}
2022-04-16 23:47:11,757   INFO       client.py             Сформировано presence сообщение: {'action': 'presence', 'time': 1650142031.757958, 'user': {'account_name': 'test2'}}
2022-04-16 23:47:11,768   DEBUG      client.py             Вызвана функция: send_message с параметрами: (<socket.socket fd=468, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58447), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1650142031.7439682, 'user': {'account_name': 'test3'}}), {}. Результат работы функции: None. Вызов из функции: init_socket 
2022-04-16 23:47:11,779   DEBUG      client.py             Вызвана функция: get_message с параметрами: (<socket.socket fd=468, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58447), raddr=('127.0.0.1', 7777)>,), {}. Результат работы функции: {'status_code': 200, 'status': 'OK'}. Вызов из функции: init_socket 
2022-04-16 23:47:11,779   DEBUG      client.py             Разбор ответа от сервера: {'status_code': 200, 'status': 'OK'}
2022-04-16 23:47:11,779   INFO       client.py             Установленно соединение с сервером. Ответ сервера: 200: OK
2022-04-16 23:47:11,781   DEBUG      client.py             Вызвана функция: send_message с параметрами: (<socket.socket fd=352, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58448), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1650142031.7539608, 'user': {'account_name': 'test1'}}), {}. Результат работы функции: None. Вызов из функции: init_socket 
2022-04-16 23:47:11,784   DEBUG      client.py             Вызвана функция: send_message с параметрами: (<socket.socket fd=416, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58449), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1650142031.757958, 'user': {'account_name': 'test2'}}), {}. Результат работы функции: None. Вызов из функции: init_socket 
2022-04-16 23:47:11,803   DEBUG      client.py             Вызвана функция: get_message с параметрами: (<socket.socket fd=352, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58448), raddr=('127.0.0.1', 7777)>,), {}. Результат работы функции: {'status_code': 200, 'status': 'OK'}. Вызов из функции: init_socket 
2022-04-16 23:47:11,803   DEBUG      client.py             Разбор ответа от сервера: {'status_code': 200, 'status': 'OK'}
2022-04-16 23:47:11,803   INFO       client.py             Установленно соединение с сервером. Ответ сервера: 200: OK
2022-04-16 23:47:11,818   DEBUG      client.py             Запущены процессы получения и отправки сообщений.
2022-04-16 23:47:11,823   DEBUG      client.py             Запущены процессы получения и отправки сообщений.
2022-04-16 23:47:11,826   DEBUG      client.py             Вызвана функция: get_message с параметрами: (<socket.socket fd=416, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58449), raddr=('127.0.0.1', 7777)>,), {}. Результат работы функции: {'status_code': 200, 'status': 'OK'}. Вызов из функции: init_socket 
2022-04-16 23:47:11,826   DEBUG      client.py             Разбор ответа от сервера: {'status_code': 200, 'status': 'OK'}
2022-04-16 23:47:11,826   INFO       client.py             Установленно соединение с сервером. Ответ сервера: 200: OK
2022-04-16 23:47:11,832   DEBUG      client.py             Запущены процессы получения и отправки сообщений.
2022-04-16 23:47:39,184   INFO       client.py             Сформировано presence сообщение: {'action': 'presence', 'time': 1650142059.183014, 'user': {'account_name': 'test1'}}
2022-04-16 23:47:39,205   DEBUG      client.py             Вызвана функция: send_message с параметрами: (<socket.socket fd=520, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58459), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1650142059.183014, 'user': {'account_name': 'test1'}}), {}. Результат работы функции: None. Вызов из функции: init_socket 
2022-04-16 23:47:39,212   INFO       client.py             Сформировано presence сообщение: {'action': 'presence', 'time': 1650142059.2129924, 'user': {'account_name': 'test2'}}
2022-04-16 23:47:39,214   DEBUG      client.py             Вызвана функция: get_message с параметрами: (<socket.socket fd=520, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58459), raddr=('127.0.0.1', 7777)>,), {}. Результат работы функции: {'status_code': 400, 'status': 'Bad Request', 'error': 'Имя пользователя уже занято.'}. Вызов из функции: init_socket 
2022-04-16 23:47:39,214   DEBUG      client.py             Разбор ответа от сервера: {'status_code': 400, 'status': 'Bad Request', 'error': 'Имя пользователя уже занято.'}
2022-04-16 23:47:39,214   INFO       client.py             Установленно соединение с сервером. Ответ сервера: 400: Bad Request, Имя пользователя уже занято.
2022-04-16 23:47:39,216   DEBUG      client.py             Запущены процессы получения и отправки сообщений.
2022-04-16 23:47:39,217   CRITICAL   client.py             Потеряно соединение с сервером.
2022-04-16 23:47:39,223   INFO       client.py             Сформировано presence сообщение: {'action': 'presence', 'time': 1650142059.2239857, 'user': {'account_name': 'test3'}}
2022-04-16 23:47:39,236   DEBUG      client.py             Вызвана функция: send_message с параметрами: (<socket.socket fd=336, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58460), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1650142059.2129924, 'user': {'account_name': 'test2'}}), {}. Результат работы функции: None. Вызов из функции: init_socket 
2022-04-16 23:47:39,237   DEBUG      client.py             Вызвана функция: get_message с параметрами: (<socket.socket fd=336, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58460), raddr=('127.0.0.1', 7777)>,), {}. Результат работы функции: {'status_code': 400, 'status': 'Bad Request', 'error': 'Имя пользователя уже занято.'}. Вызов из функции: init_socket 
2022-04-16 23:47:39,238   DEBUG      client.py             Разбор ответа от сервера: {'status_code': 400, 'status': 'Bad Request', 'error': 'Имя пользователя уже занято.'}
2022-04-16 23:47:39,238   INFO       client.py             Установленно соединение с сервером. Ответ сервера: 400: Bad Request, Имя пользователя уже занято.
2022-04-16 23:47:39,249   DEBUG      client.py             Вызвана функция: send_message с параметрами: (<socket.socket fd=276, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58461), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1650142059.2239857, 'user': {'account_name': 'test3'}}), {}. Результат работы функции: None. Вызов из функции: init_socket 
2022-04-16 23:47:39,250   DEBUG      client.py             Вызвана функция: get_message с параметрами: (<socket.socket fd=276, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58461), raddr=('127.0.0.1', 7777)>,), {}. Результат работы функции: {'status_code': 400, 'status': 'Bad Request', 'error': 'Имя пользователя уже занято.'}. Вызов из функции: init_socket 
2022-04-16 23:47:39,250   DEBUG      client.py             Разбор ответа от сервера: {'status_code': 400, 'status': 'Bad Request', 'error': 'Имя пользователя уже занято.'}
2022-04-16 23:47:39,250   INFO       client.py             Установленно соединение с сервером. Ответ сервера: 400: Bad Request, Имя пользователя уже занято.
2022-04-16 23:47:39,256   DEBUG      client.py             Запущены процессы получения и отправки сообщений.
2022-04-16 23:47:39,257   CRITICAL   client.py             Потеряно соединение с сервером.
2022-04-16 23:47:39,257   DEBUG      client.py             Запущены процессы получения и отправки сообщений.
2022-04-16 23:47:39,258   CRITICAL   client.py             Потеряно соединение с сервером.
2022-04-16 23:47:41,884   INFO       client.py             Сформировано presence сообщение: {'action': 'presence', 'time': 1650142061.884496, 'user': {'account_name': 'test2'}}
2022-04-16 23:47:41,907   DEBUG      client.py             Вызвана функция: send_message с параметрами: (<socket.socket fd=336, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58462), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1650142061.884496, 'user': {'account_name': 'test2'}}), {}. Результат работы функции: None. Вызов из функции: init_socket 
2022-04-16 23:47:41,918   DEBUG      client.py             Вызвана функция: get_message с параметрами: (<socket.socket fd=336, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58462), raddr=('127.0.0.1', 7777)>,), {}. Результат работы функции: {'status_code': 400, 'status': 'Bad Request', 'error': 'Имя пользователя уже занято.'}. Вызов из функции: init_socket 
2022-04-16 23:47:41,918   DEBUG      client.py             Разбор ответа от сервера: {'status_code': 400, 'status': 'Bad Request', 'error': 'Имя пользователя уже занято.'}
2022-04-16 23:47:41,918   INFO       client.py             Установленно соединение с сервером. Ответ сервера: 400: Bad Request, Имя пользователя уже занято.
2022-04-16 23:47:41,918   INFO       client.py             Сформировано presence сообщение: {'action': 'presence', 'time': 1650142061.9184723, 'user': {'account_name': 'test3'}}
2022-04-16 23:47:41,928   DEBUG      client.py             Запущены процессы получения и отправки сообщений.
2022-04-16 23:47:41,928   CRITICAL   client.py             Потеряно соединение с сервером.
2022-04-16 23:47:41,943   INFO       client.py             Сформировано presence сообщение: {'action': 'presence', 'time': 1650142061.9434547, 'user': {'account_name': 'test1'}}
2022-04-16 23:47:41,961   DEBUG      client.py             Вызвана функция: send_message с параметрами: (<socket.socket fd=308, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58463), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1650142061.9184723, 'user': {'account_name': 'test3'}}), {}. Результат работы функции: None. Вызов из функции: init_socket 
2022-04-16 23:47:41,962   DEBUG      client.py             Вызвана функция: get_message с параметрами: (<socket.socket fd=308, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58463), raddr=('127.0.0.1', 7777)>,), {}. Результат работы функции: {'status_code': 400, 'status': 'Bad Request', 'error': 'Имя пользователя уже занято.'}. Вызов из функции: init_socket 
2022-04-16 23:47:41,962   DEBUG      client.py             Разбор ответа от сервера: {'status_code': 400, 'status': 'Bad Request', 'error': 'Имя пользователя уже занято.'}
2022-04-16 23:47:41,962   INFO       client.py             Установленно соединение с сервером. Ответ сервера: 400: Bad Request, Имя пользователя уже занято.
2022-04-16 23:47:41,966   DEBUG      client.py             Запущены процессы получения и отправки сообщений.
2022-04-16 23:47:41,967   CRITICAL   client.py             Потеряно соединение с сервером.
2022-04-16 23:47:41,972   DEBUG      client.py             Вызвана функция: send_message с параметрами: (<socket.socket fd=332, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58464), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1650142061.9434547, 'user': {'account_name': 'test1'}}), {}. Результат работы функции: None. Вызов из функции: init_socket 
2022-04-16 23:47:41,973   DEBUG      client.py             Вызвана функция: get_message с параметрами: (<socket.socket fd=332, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58464), raddr=('127.0.0.1', 7777)>,), {}. Результат работы функции: {'status_code': 400, 'status': 'Bad Request', 'error': 'Имя пользователя уже занято.'}. Вызов из функции: init_socket 
2022-04-16 23:47:41,973   DEBUG      client.py             Разбор ответа от сервера: {'status_code': 400, 'status': 'Bad Request', 'error': 'Имя пользователя уже занято.'}
2022-04-16 23:47:41,973   INFO       client.py             Установленно соединение с сервером. Ответ сервера: 400: Bad Request, Имя пользователя уже занято.
2022-04-16 23:47:41,974   DEBUG      client.py             Запущены процессы получения и отправки сообщений.
2022-04-16 23:47:41,975   CRITICAL   client.py             Потеряно соединение с сервером.
2022-04-16 23:47:44,411   INFO       client.py             Сформировано presence сообщение: {'action': 'presence', 'time': 1650142064.4115655, 'user': {'account_name': 'test3'}}
2022-04-16 23:47:44,439   DEBUG      client.py             Вызвана функция: send_message с параметрами: (<socket.socket fd=372, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58465), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1650142064.4115655, 'user': {'account_name': 'test3'}}), {}. Результат работы функции: None. Вызов из функции: init_socket 
2022-04-16 23:47:44,443   INFO       client.py             Сформировано presence сообщение: {'action': 'presence', 'time': 1650142064.4435427, 'user': {'account_name': 'test1'}}
2022-04-16 23:47:44,446   DEBUG      client.py             Вызвана функция: get_message с параметрами: (<socket.socket fd=372, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58465), raddr=('127.0.0.1', 7777)>,), {}. Результат работы функции: {'status_code': 400, 'status': 'Bad Request', 'error': 'Имя пользователя уже занято.'}. Вызов из функции: init_socket 
2022-04-16 23:47:44,446   DEBUG      client.py             Разбор ответа от сервера: {'status_code': 400, 'status': 'Bad Request', 'error': 'Имя пользователя уже занято.'}
2022-04-16 23:47:44,446   INFO       client.py             Установленно соединение с сервером. Ответ сервера: 400: Bad Request, Имя пользователя уже занято.
2022-04-16 23:47:44,467   DEBUG      client.py             Вызвана функция: send_message с параметрами: (<socket.socket fd=404, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58466), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1650142064.4435427, 'user': {'account_name': 'test1'}}), {}. Результат работы функции: None. Вызов из функции: init_socket 
2022-04-16 23:47:44,486   DEBUG      client.py             Запущены процессы получения и отправки сообщений.
2022-04-16 23:47:44,487   CRITICAL   client.py             Потеряно соединение с сервером.
2022-04-16 23:47:44,510   DEBUG      client.py             Вызвана функция: get_message с параметрами: (<socket.socket fd=404, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58466), raddr=('127.0.0.1', 7777)>,), {}. Результат работы функции: {'status_code': 400, 'status': 'Bad Request', 'error': 'Имя пользователя уже занято.'}. Вызов из функции: init_socket 
2022-04-16 23:47:44,510   DEBUG      client.py             Разбор ответа от сервера: {'status_code': 400, 'status': 'Bad Request', 'error': 'Имя пользователя уже занято.'}
2022-04-16 23:47:44,510   INFO       client.py             Установленно соединение с сервером. Ответ сервера: 400: Bad Request, Имя пользователя уже занято.
2022-04-16 23:47:44,510   INFO       client.py             Сформировано presence сообщение: {'action': 'presence', 'time': 1650142064.5104954, 'user': {'account_name': 'test2'}}
2022-04-16 23:47:44,534   DEBUG      client.py             Запущены процессы получения и отправки сообщений.
2022-04-16 23:47:44,537   DEBUG      client.py             Вызвана функция: send_message с параметрами: (<socket.socket fd=436, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58468), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1650142064.5104954, 'user': {'account_name': 'test2'}}), {}. Результат работы функции: None. Вызов из функции: init_socket 
2022-04-16 23:47:44,534   CRITICAL   client.py             Потеряно соединение с сервером.
2022-04-16 23:47:45,018   DEBUG      client.py             Вызвана функция: get_message с параметрами: (<socket.socket fd=436, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58468), raddr=('127.0.0.1', 7777)>,), {}. Результат работы функции: {'status_code': 400, 'status': 'Bad Request', 'error': 'Имя пользователя уже занято.'}. Вызов из функции: init_socket 
2022-04-16 23:47:45,018   DEBUG      client.py             Разбор ответа от сервера: {'status_code': 400, 'status': 'Bad Request', 'error': 'Имя пользователя уже занято.'}
2022-04-16 23:47:45,018   INFO       client.py             Установленно соединение с сервером. Ответ сервера: 400: Bad Request, Имя пользователя уже занято.
2022-04-16 23:47:45,019   DEBUG      client.py             Запущены процессы получения и отправки сообщений.
2022-04-16 23:47:45,019   CRITICAL   client.py             Потеряно соединение с сервером.
2022-04-16 23:47:46,960   INFO       client.py             Сформировано presence сообщение: {'action': 'presence', 'time': 1650142066.9607599, 'user': {'account_name': 'test2'}}
2022-04-16 23:47:46,963   INFO       client.py             Сформировано presence сообщение: {'action': 'presence', 'time': 1650142066.9627576, 'user': {'account_name': 'test3'}}
2022-04-16 23:47:46,964   INFO       client.py             Сформировано presence сообщение: {'action': 'presence', 'time': 1650142066.9647567, 'user': {'account_name': 'test1'}}
2022-04-16 23:47:46,984   DEBUG      client.py             Вызвана функция: send_message с параметрами: (<socket.socket fd=392, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58471), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1650142066.9627576, 'user': {'account_name': 'test3'}}), {}. Результат работы функции: None. Вызов из функции: init_socket 
2022-04-16 23:47:46,985   DEBUG      client.py             Вызвана функция: get_message с параметрами: (<socket.socket fd=392, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58471), raddr=('127.0.0.1', 7777)>,), {}. Результат работы функции: {'status_code': 400, 'status': 'Bad Request', 'error': 'Имя пользователя уже занято.'}. Вызов из функции: init_socket 
2022-04-16 23:47:46,985   DEBUG      client.py             Разбор ответа от сервера: {'status_code': 400, 'status': 'Bad Request', 'error': 'Имя пользователя уже занято.'}
2022-04-16 23:47:46,985   INFO       client.py             Установленно соединение с сервером. Ответ сервера: 400: Bad Request, Имя пользователя уже занято.
2022-04-16 23:47:46,986   DEBUG      client.py             Вызвана функция: send_message с параметрами: (<socket.socket fd=376, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58472), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1650142066.9647567, 'user': {'account_name': 'test1'}}), {}. Результат работы функции: None. Вызов из функции: init_socket 
2022-04-16 23:47:46,987   DEBUG      client.py             Вызвана функция: get_message с параметрами: (<socket.socket fd=376, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58472), raddr=('127.0.0.1', 7777)>,), {}. Результат работы функции: {'status_code': 400, 'status': 'Bad Request', 'error': 'Имя пользователя уже занято.'}. Вызов из функции: init_socket 
2022-04-16 23:47:46,987   DEBUG      client.py             Разбор ответа от сервера: {'status_code': 400, 'status': 'Bad Request', 'error': 'Имя пользователя уже занято.'}
2022-04-16 23:47:46,987   INFO       client.py             Установленно соединение с сервером. Ответ сервера: 400: Bad Request, Имя пользователя уже занято.
2022-04-16 23:47:46,989   DEBUG      client.py             Вызвана функция: send_message с параметрами: (<socket.socket fd=356, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58470), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1650142066.9607599, 'user': {'account_name': 'test2'}}), {}. Результат работы функции: None. Вызов из функции: init_socket 
2022-04-16 23:47:46,990   DEBUG      client.py             Вызвана функция: get_message с параметрами: (<socket.socket fd=356, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 58470), raddr=('127.0.0.1', 7777)>,), {}. Результат работы функции: {'status_code': 400, 'status': 'Bad Request', 'error': 'Имя пользователя уже занято.'}. Вызов из функции: init_socket 
2022-04-16 23:47:46,991   DEBUG      client.py             Разбор ответа от сервера: {'status_code': 400, 'status': 'Bad Request', 'error': 'Имя пользователя уже занято.'}
2022-04-16 23:47:46,991   INFO       client.py             Установленно соединение с сервером. Ответ сервера: 400: Bad Request, Имя пользователя уже занято.
2022-04-16 23:47:46,992   DEBUG      client.py             Запущены процессы получения и отправки сообщений.
2022-04-16 23:47:46,992   CRITICAL   client.py             Потеряно соединение с сервером.
2022-04-16 23:47:46,992   DEBUG      client.py             Запущены процессы получения и отправки сообщений.
2022-04-16 23:47:46,995   DEBUG      client.py             Запущены процессы получения и отправки сообщений.
2022-04-16 23:47:46,995   CRITICAL   client.py             Потеряно соединение с сервером.
2022-04-16 23:47:46,993   CRITICAL   client.py             Потеряно соединение с сервером.
